mongoexport --db ventas --collection accounts --out accounts.json
mongoexport --db ventas --collection admingroups --out admingroups.json
mongoexport --db ventas --collection admins --out admins.json
mongoexport --db ventas --collection areas --out areas.json
mongoexport --db ventas --collection campos --out campos.json
mongoexport --db ventas --collection categories --out categories.json
mongoexport --db ventas --collection clientes --out clientes.json
mongoexport --db ventas --collection cuestionarios --out cuestionarios.json
mongoexport --db ventas --collection empresas --out empresas.json
mongoexport --db ventas --collection establecimientos --out establecimientos.json
mongoexport --db ventas --collection facturas --out facturas.json
mongoexport --db ventas --collection indicadors --out indicadors.json
mongoexport --db ventas --collection inventarios --out inventarios.json
mongoexport --db ventas --collection loginattempts --out loginattempts.json
mongoexport --db ventas --collection menus --out menus.json
mongoexport --db ventas --collection nivels --out nivels.json
mongoexport --db ventas --collection proveedors --out proveedors.json
mongoexport --db ventas --collection users --out users.json
mongoexport --db ventas --collection vendedor --out vendedor.json
