mongoimport --db ventas --collection accounts --collection accounts --drop --file accounts.json
mongoimport --db ventas --collection admingroups --collection admingroups --drop --file admingroups.json
mongoimport --db ventas --collection admins --collection admins --drop --file admins.json
mongoimport --db ventas --collection areas --collection areas --drop --file areas.json
mongoimport --db ventas --collection campos --collection campos --drop --file campos.json
mongoimport --db ventas --collection categories --collection categories --drop --file categories.json
mongoimport --db ventas --collection clientes --collection clientes --drop --file clientes.json
mongoimport --db ventas --collection cuestionarios --collection cuestionarios --drop --file cuestionarios.json
mongoimport --db ventas --collection empresas --collection empresas --drop --file empresas.json
mongoimport --db ventas --collection establecimientos --collection establecimientos --drop --file establecimientos.json
mongoimport --db ventas --collection facturas --collection facturas --drop --file facturas.json
mongoimport --db ventas --collection impresos --collection impresos --drop --file impresos.json
mongoimport --db ventas --collection indicadors --collection indicadors --drop --file indicadors.json
mongoimport --db ventas --collection inventarios --collection inventarios --drop --file inventarios.json
mongoimport --db ventas --collection menus --collection menus --drop --file menus.json
mongoimport --db ventas --collection nivels --collection nivels --drop --file nivels.json
mongoimport --db ventas --collection proveedors --collection proveedors --drop --file proveedors.json
mongoimport --db ventas --collection templates --collection templates --drop --file templates.json
mongoimport --db ventas --collection users --collection users --drop --file users.json
mongoimport --db ventas --collection vendedor --collection vendedor --drop --file vendedor.json
