mongoimport --db ventas --collection accounts --collection accounts --drop --file accounts.json
mongoimport --db ventas --collection admingroups --collection accounts --drop --file admingroups.json
mongoimport --db ventas --collection admins --collection accounts --drop --file admins.json
mongoimport --db ventas --collection areas --collection accounts --drop --file areas.json
mongoimport --db ventas --collection campos --collection accounts --drop --file campos.json
mongoimport --db ventas --collection categories --collection accounts --drop --file categories.json
mongoimport --db ventas --collection clientes --collection accounts --drop --file clientes.json
mongoimport --db ventas --collection cuestionarios --collection accounts --drop --file cuestionarios.json
mongoimport --db ventas --collection empresas --collection accounts --drop --file empresas.json
mongoimport --db ventas --collection establecimientos --collection accounts --drop --file establecimientos.json
mongoimport --db ventas --collection facturas --collection accounts --drop --file facturas.json
mongoimport --db ventas --collection impresos --collection accounts --drop --file impresos.json
mongoimport --db ventas --collection indicadors --collection accounts --drop --file indicadors.json
mongoimport --db ventas --collection inventarios --collection accounts --drop --file inventarios.json
mongoimport --db ventas --collection menus --collection accounts --drop --file menus.json
mongoimport --db ventas --collection nivels --collection accounts --drop --file nivels.json
mongoimport --db ventas --collection proveedors --collection accounts --drop --file proveedors.json
mongoimport --db ventas --collection templates --collection accounts --drop --file templates.json
mongoimport --db ventas --collection users --collection accounts --drop --file users.json
mongoimport --db ventas --collection vendedor --collection accounts --drop --file vendedor.json
